### ISSUE TITLE
[Question] TypeScript vs JavaScript

### ISSUE THREAD

**Issue by IceSentry** [matt77hias/smallpt#1]
Why is the TypeScript version slower than the JavaScript version? It uses the exact same runtime.

**Comment by matt77hias** [comment]
The JavaScript code after trans-compiling the TypeScript/CoffeeScript project is not 1-1 identical to the JavaScript project.

**Comment by IceSentry** [comment]
In that case the benchmark is simply comparing 2 different javascript implementations. Typescript is not a runtime environment so it's not really comparing javascript vs typescript vs every other implementation.

In any case this repo is still interestig, I just found it a little bit surprising to see js and ts with different result on a performance benchmark.

**Comment by matt77hias** [comment]
True (actually three if you include CoffeeScript which trans-compiles to JavaScript as well). If one considers JavaScript as some sort of assembly language for the web, some similar situation exists for the languages compiling to the same real (e.g., C vs C++) or abstract (e.g., Java vs Scala) assembly language as well. In which case the differences are partially due to the source code and partially due to the compiler/transcompiler/interpreter etc.
¯\\_(ツ)_/¯

It is of course completely possible (and probably is) that my TypeScript code is far from optimal, as I am not that familiar with web languages. My primary aim is just to have some basic reference of how to code some basic functionality (e.g., random number generation, file IO, etc.) in all of these languages. The benchmark is just some far from scientific side activity. 😄
